### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'segment_anything'

### ISSUE THREAD

**Issue by halumice** [continue-revolution/sd-webui-segment-anything#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

after instalation. Trying to reproduce video guide. 

Looks like a python prerequisite.

### Steps to reproduce the problem

1. Lauch webUI and see the message

### What should have happened?

Normal launch, extension "section" should be in img2img but it is not

### Commit where the problem happens

webui: 22bcc7b
controlnet: 

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--xformers --medvram
```

### Console logs

```Shell
Traceback (most recent call last):
  File "E:\Files\SD_auto\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\Files\SD_auto\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Files\SD_auto\stable-diffusion-webui\extensions\sd-webui-segment-everything\scripts\sam.py", line 20, in <module>
    from segment_anything import SamPredictor, build_sam
ModuleNotFoundError: No module named 'segment_anything'
```

**Comment by halumice** [comment]
I installed manually with pip install because it was not getting installed automatically
![imagen](https://user-images.githubusercontent.com/128826833/230963782-33474002-76b0-4d08-97ba-1ae59f996f2d.png)

But anyways:
![imagen](https://user-images.githubusercontent.com/128826833/230964138-7085ddae-7c08-426f-8ddd-11d173f8ba9c.png)

Any advice? 

Thanks, I think your extension will be a turning point in inpainting

**Comment by continue-revolution** [comment]
The reason might be because your sd-webui python environment is using a different python environment. I have replaced my automatic pip install script with the global run_pip, could you try again?

**Comment by halumice** [comment]
Yep! It is fixed now. Thanks!

**Comment by continue-revolution** [comment]
> > The reason might be because your sd-webui python environment is using a different python environment. I have replaced my automatic pip install script with the global run_pip, could you try again?
> 
> how do you do that? I'm getting this:
> 
> ModuleNotFoundError: No module named 'modules.paths_internal'

This is because you have not updated your SD webui to the newest version. You should probably add [this](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/paths_internal.py) file under `${webui}/modules`. Not sure whether it will work. If it is not working, let me know.

**Comment by continue-revolution** [comment]
> Thank you! Is there a way to automatically update it upon opening the 1111 webui? I thought git pill did that in the webui-user file

Yes. Run `git pull` under your `${webui}` directory is all you need.

**Comment by ljleb** [comment]
Consider installing the requirements in the `install.py` file: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Developing-extensions

**Comment by continue-revolution** [comment]
> Consider installing the requirements in the `install.py` file: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Developing-extensions

Done

**Comment by sirosann** [comment]
Maybe your conda env is wrong
