### ISSUE TITLE
点击图片没反应

### ISSUE THREAD

**Issue by liulanghan8023** [continue-revolution/sd-webui-segment-anything#10]
![image](https://user-images.githubusercontent.com/18147008/231218263-2e28c714-207d-4e90-9b43-ca3f747f9f25.png)
点击图片没反应
使用谷歌的colab部署
希望帮忙看下，非常感谢！

**Comment by continue-revolution** [comment]
> 可以了，谢谢！ 要是画笔能调整大小，能撤回就更好了

大小不能调整，因为没有画笔，你只是打了个点，圆心就是SAM输入的坐标。撤回只需要左键你打的点，红点黑点都是这样操作。

**Comment by whitepapercg** [comment]
> > 可以了，谢谢！ 要是画笔能调整大小，能撤回就更好了
> 
> 大小不能调整，因为没有画笔，你只是打了个点，圆心就是SAM输入的坐标。撤回只需要左键你打的点，红点黑点都是这样操作。

It didn't help me. The same problem.
Tried different browsers. Also updated automatik and your extension. Installed all the dependencies. No luck

**Comment by continue-revolution** [comment]
> > > 可以了，谢谢！ 要是画笔能调整大小，能撤回就更好了
> > 
> > 
> > 大小不能调整，因为没有画笔，你只是打了个点，圆心就是SAM输入的坐标。撤回只需要左键你打的点，红点黑点都是这样操作。
> 
> It didn't help me. The same problem. Tried different browsers. Also updated automatik and your extension. Installed all the dependencies. No luck
> 
> ps: No errors or alerts in the console when doing this

This is strange. By “console” do you mean both terminal and you browser console log? Ther should be some error message on at least one of them.

**Comment by watersliang** [comment]
我也遇到了这个问题，比较奇怪的是，我一台设备是正常的，另一台设备则不能点击添加红点和黑点，终端也没有任何报错。我两台设备的SD版本是一致的，仅安装的插件有一些区别。

**Comment by watersliang** [comment]
> 我也遇到了这个问题，比较奇怪的是，我一台设备是正常的，另一台设备则不能点击添加红点和黑点，终端也没有任何报错。我两台设备的SD版本是一致的，仅安装的插件有一些区别。

补充一点信息： 在右键的时候，出现了在浏览器上邮件常规图片时会出现的菜单。
![image](https://user-images.githubusercontent.com/76990369/232441397-73ce113d-52fb-4fe5-a751-e2aaf7867aec.png)

**Comment by continue-revolution** [comment]
> 我也遇到了这个问题，比较奇怪的是，我一台设备是正常的，另一台设备则不能点击添加红点和黑点，终端也没有任何报错。我两台设备的SD版本是一致的，仅安装的插件有一些区别。

你能不能告诉我，你在这个不能正常使用我的插件的设备上，下载了哪些能正常使用我插件的设备没有下载的插件。

**Comment by watersliang** [comment]
> > 我也遇到了这个问题，比较奇怪的是，我一台设备是正常的，另一台设备则不能点击添加红点和黑点，终端也没有任何报错。我两台设备的SD版本是一致的，仅安装的插件有一些区别。
> 
> 你能不能告诉我，你在这个不能正常使用我的插件的设备上，下载了哪些能正常使用我插件的设备没有下载的插件。

![image](https://user-images.githubusercontent.com/76990369/232442075-9d1b47f1-7a7a-436f-a08c-ee152ecc77ac.png)
![image](https://user-images.githubusercontent.com/76990369/232442327-28dcbe08-7294-403e-a272-ec688dbd032e.png)
sd_web_ui_preset_utils 和 sd-webui-supermerger 是有问题的设备没有安装的插件

**Comment by continue-revolution** [comment]
好奇怪，我有点不明白为什么插件装多了反而问题还抵消了。

**Comment by watersliang** [comment]
> 好奇怪，我有点不明白为什么插件装多了反而问题还抵消了。

我怀疑可能还是设备环境问题，比如 右键添加红点需要的一些依赖环境之类

**Comment by watersliang** [comment]
> > 好奇怪，我有点不明白为什么插件装多了反而问题还抵消了。
> 
> 我怀疑可能还是设备环境问题，比如 右键添加红点需要的一些依赖环境之类

我又做了一次对照测试，我将我那台问题设备开放了局域网访问，然后 在本机能正常使用本插件的那个浏览器上，我使用地址和端口打开了webui，还是不能正常的添加黑点和红点。说明还是webui和插件的问题。

**Comment by continue-revolution** [comment]
> > > 好奇怪，我有点不明白为什么插件装多了反而问题还抵消了。
> > 
> > 
> > 我怀疑可能还是设备环境问题，比如 右键添加红点需要的一些依赖环境之类
> 
> 我又做了一次对照测试，我将我那台问题设备开放了局域网访问，然后 在本机能正常使用本插件的那个浏览器上，我使用地址和端口打开了webui，还是不能正常的添加黑点和红点。说明还是webui和插件的问题。

你有空的话能不能帮我在你的问题设备上把缺少的插件装上，或者是在你没问题的设备上把多余的插件暂时挪到别的的文件夹，看看会怎么样。

**Comment by continue-revolution** [comment]
然后如果有问题的话帮我看看浏览器console和终端，看看有没有什么exception

**Comment by watersliang** [comment]
> > > > 好奇怪，我有点不明白为什么插件装多了反而问题还抵消了。
> > > 
> > > 
> > > 我怀疑可能还是设备环境问题，比如 右键添加红点需要的一些依赖环境之类
> > 
> > 
> > 我又做了一次对照测试，我将我那台问题设备开放了局域网访问，然后 在本机能正常使用本插件的那个浏览器上，我使用地址和端口打开了webui，还是不能正常的添加黑点和红点。说明还是webui和插件的问题。
> 
> 你有空的话能不能帮我在你的问题设备上把缺少的插件装上，或者是在你没问题的设备上把多余的插件暂时挪到别的的文件夹，看看会怎么样。

我把插件差的插件都加上了，但依然不能使用。浏览器console 确实有错误
![image](https://user-images.githubusercontent.com/76990369/232451864-f283f993-6ed1-47df-bce0-998c5839e4fd.png)

**Comment by continue-revolution** [comment]
终端有报错吗，指的是启动webui的命令行

**Comment by watersliang** [comment]
> 终端有报错吗，指的是启动webui的命令行

![image](https://user-images.githubusercontent.com/76990369/232453198-275afdd5-c48d-4855-811b-f9c37dd744b1.png)
终端没有报错

**Comment by continue-revolution** [comment]
这也太逆天了，感觉没有办法复现。

**Comment by watersliang** [comment]
> 这也太逆天了，感觉没有办法复现。

![image](https://user-images.githubusercontent.com/76990369/232454512-fa21387c-7fb9-424d-a9ba-0c1a82e9de74.png)
remove all points的时候 会出现这个。在正常的设备上，即使图片上的红点黑点都已经移除了后再次点击，也不会出现这个报错。

**Comment by continue-revolution** [comment]
你的问题设备上webui是最新版（2开头hash）吗，如果是，就帮我点进那个Button.svelte:10看看里面是啥吧

**Comment by watersliang** [comment]
> 你的问题设备上webui是最新版（2开头hash）吗，如果是，就帮我点进那个Button.svelte:10看看里面是啥吧

![image](https://user-images.githubusercontent.com/76990369/232477349-e646ea06-e35d-46cb-bb03-c6e5ec501b3c.png)

Button.svelte 的路径是什么

**Comment by continue-revolution** [comment]
就是你 浏览器console那儿报错里面的

**Comment by watersliang** [comment]
> 就是你 浏览器console那儿报错里面的

![image](https://user-images.githubusercontent.com/76990369/232478934-26773acb-b785-404c-b201-ad6f3b6b7fca.png)

**Comment by w73w030** [comment]
我遇到和你一样的问题~  请问你的问题得到解决了吗？

**Comment by cdmusic2019** [comment]
这个有可能是系统的原因，比如CSS，曾经我这台机器安装 SD时打开都是乱码。是因为安装DW时，软件修改了CSS。YT上有个UP主说，换个浏览器也许能解决。
