### ISSUE TITLE
[Bug]: No such file or directory: '/home/yhd233/automatic/local_groundingdino/requirements_groundingdino.txt

### ISSUE THREAD

**Issue by YHD233** [continue-revolution/sd-webui-segment-anything#109]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you updated WebUI and this extension to the newest version?

- [X] I have updated WebUI and this extension to the most up-to-date version

### Do you understand that you should go to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues if you cannot install GroundingDINO?

- [X] My problem is not about installing GroundingDINO

### Do you know that you should use the newest ControlNet extension and enable external control if you want SAM extension to control ControlNet?

- [X] I have updated ControlNet extension and enabled "Allow other script to control this extension"

### What happened?

运行不了，出错提示：No such file or directory: '/home/yhd233/automatic/local_groundingdino/requirements_groundingdino.txt

### Steps to reproduce the problem

1，批量处理
2，提示词和目录填好
3，Output per image：1 勾选Save masked image和Save mask
4，Start batch process

### What should have happened?

正常批量运行

### Commit where the problem happens

webui: vlad automatic
extension: 
sd-webui-segment-anything
系统Kubuntu 22.04 x86_64
CPU：12400f
GPU：RX6800

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--disable-safe-unpickle --skip-git --skip-requirements --skip-torch --skip-extensions --autolaunch --port 7860 --medvram
```
### Console logs
[error.log](https://github.com/continue-revolution/sd-webui-segment-anything/files/11628090/error.log)

**Comment by YHD233** [comment]
设置里打开本地groundingdino就能用了，RX6800也能正常调用

**Comment by continue-revolution** [comment]
确实有点bug，等会就会更新。
