### ISSUE TITLE
关于界面美化的两个小问题

### ISSUE THREAD

**Issue by kkoib** [continue-revolution/sd-webui-segment-anything#11]
1.请问你的双语界面样式是自己改的吗？我看插件库里的双语插件是上下排布很不美观，你的样式局部更加合理

<img width="902" alt="Snipaste_2023-04-12_01-33-58" src="https://user-images.githubusercontent.com/17550113/231243434-5fd62aaf-c7e0-49cb-84be-8b0f55b5d088.png">
<img width="1018" alt="Snipaste_2023-04-12_01-28-54" src="https://user-images.githubusercontent.com/17550113/231243209-5591c38a-c8f8-4b97-ad12-7ec156833d81.png">

2.我看你的插件界面非常工整，请问插件的位置顺序可以改的吗？
<img width="816" alt="Snipaste_2023-04-12_01-29-10" src="https://user-images.githubusercontent.com/17550113/231244039-41872034-d8db-47b3-b6f9-4256f1759ece.png">

**Comment by continue-revolution** [comment]
1. 我没有改，从一开始就是这样。我用的是[这个插件](https://github.com/VinsonLaro/stable-diffusion-webui-chinese)
2. 插件顺序由文件夹名字决定，如果你想调整顺序，可以尝试修改插件文件名，但是我个人不推荐，因为可能某些插件（比如我写的这个插件的早期版本）会把文件夹名字写死导致插件不可用。似乎无法从设置中直接修改。

**Comment by kkoib** [comment]
十分感谢！谢谢你做的一切！
