### ISSUE TITLE
[Bug]: TypeError: 'float' object is not subscriptable

### ISSUE THREAD

**Issue by 519571754** [continue-revolution/sd-webui-segment-anything#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you updated WebUI and this extension to the latest version?

- [X] I have updated WebUI and this extension to the latest version

### Do you understand that you should read the 1st item of https://github.com/continue-revolution/sd-webui-segment-anything#faq if you cannot install GroundingDINO?

- [X] My problem is not about installing GroundingDINO

### Do you understand that you should use the latest ControlNet extension and enable external control if you want SAM extension to control ControlNet?

- [X] I have updated ControlNet extension and enabled "Allow other script to control this extension"

### Do you understand that you should read the 2nd item of https://github.com/continue-revolution/sd-webui-segment-anything#faq if you observe problems like AttributeError bool object has no attribute enabled and TypeError bool object is not subscriptable?

- [X] My problem is not about such issue, otherwise I have tried changing the extension directory name from sd-webui-segment-anything to a1111-sd-webui-segment-anything

### What happened?

我更新了ControlNet v1.1.219 ，之后，然后仅仅使用ControlNet v1.1.219去做文生图任务，并没有启用segment-anything，之后就报了如下错误，我大概估计应该是ControlNet v1.1.219今天更新了一些代码，影响了segment-anything的调用，请您查看一下，万分感谢。
![info](https://github.com/continue-revolution/sd-webui-segment-anything/assets/35244965/b852a141-d5c6-4e75-88f5-edae770426fa)

### Steps to reproduce the problem

1. 更新了ControlNet v1.1.219
2. 文生图仅使用ControlNet v1.1.219
3.segment-anything报错，无法使用ControlNet v1.1.219

### What should have happened?

ControlNet v1.1.219文生图应该是正常的

### Commit where the problem happens

webui: commit baf6946
extension: ControlNet v1.1.219 commit 99408b9

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
No
```

**Comment by continue-revolution** [comment]
我无法复现你的问题，你可以试一下issue checklist的最后一条。

**Comment by 519571754** [comment]
> 我无法复现你的问题，你可以试一下issue checklist的最后一条。
请问 是issue的哪一个。

**Comment by 519571754** [comment]
> My problem is not about such issue, otherwise I have tried changing the extension directory name from sd-webui-segment-anything to a1111-sd-webui-segment-anything

Thanks。I'll try it.

**Comment by 519571754** [comment]
> My problem is not about such issue, otherwise I have tried changing the extension directory name from sd-webui-segment-anything to a1111-sd-webui-segment-anything

It worked for me！！！Thanks.
