### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Meerkov** [continue-revolution/sd-webui-segment-anything#121]
https://github.com/continue-revolution/sd-webui-segment-anything/blob/1c5e5e93be919a57d3054d4bc19e21d5b60d43a4/scripts/sam.py#LL206C94-L206C103

Should say "discarded" not "disgarded"

**Comment by continue-revolution** [comment]
fixed via https://github.com/continue-revolution/sd-webui-segment-anything/commit/6197446d2f60d206170db915d4000e73a407e2e7
