### ISSUE TITLE
[Feature]: How can I add multiple "sam_positive_points" when I use the api?

### ISSUE THREAD

**Issue by Bruce337f** [continue-revolution/sd-webui-segment-anything#130]
### Expected behavior

Or what format symbol is used to separate them, consecutive list values?

"sam_positive_points": List[List(float)], #[optional] N * 2 list of positive points in python list.
"sam_negative_points": List[List(float)], #[Optional] N * 2 negative point hints in python list.

**Comment by continue-revolution** [comment]
They both expect a list of list, where the inner list is (x, y) coordinate on the original image.

**Comment by continue-revolution** [comment]
There should be no “(“ or “)”. All brackets should be “[“ or “]”.

Black dots are positive points; red dots are negative points
