### ISSUE TITLE
[Feature]: Matt Anything (MAM)

### ISSUE THREAD

**Issue by ghpkishore** [continue-revolution/sd-webui-segment-anything#131]
### Expected behavior

Hi! thanks for adding SAM-HQ. There is MAM (https://github.com/SHI-Labs/Matting-Anything) which is incredible. Would want to know if you guys were planning to add that to the repo.

**Comment by ghpkishore** [comment]
Closing this as it is visible that it will be added in v2.

**Comment by ghpkishore** [comment]
@continue-revolution thanks for mentioning that. I didn't know it was a TODO. You mentioned it will be supported in v1.6.1. I wanted to know if you have any timelines for that. I am currently working with their gradio demo, which is still fine. But would love it in this extension.

**Comment by continue-revolution** [comment]
I cannot give you an exact timeline. Maybe tomorrow, maybe next week, subject to my availability and the implementation difficulty.

That said, Matt-anything is my first priority.
