### ISSUE TITLE
[Feature]: 只生成2号结果,速度会更快吗?

### ISSUE THREAD

**Issue by hahajaja** [continue-revolution/sd-webui-segment-anything#142]
### Expected behavior

![image](https://github.com/continue-revolution/sd-webui-segment-anything/assets/23209894/a04e44fc-ee1e-4a10-a638-f5f674e0d6cb)
0号和1号结果图像很多时候都不全

**Comment by continue-revolution** [comment]
速度上来讲不可能，因为如果sam只出一个mask就会出0号。
