### ISSUE TITLE
[Feature] Expose this extension through an API

### ISSUE THREAD

**Issue by jordan-barrett-jm** [continue-revolution/sd-webui-segment-anything#15]
I'd like to write a feature to expose this model through the segment webui API. This would be pretty straightforward to accomplish but ideally, the endpoint would not accept dots as the prompt, but text. When do you think the integration with Grounded DINO would be completed? It's something I've worked on before so if you haven't started yet I could probably knock it out today.

**Comment by jordan-barrett-jm** [comment]
Also would be ideal for https://github.com/continue-revolution/sd-webui-segment-anything/pull/12 to be merged so I can avoid conflicts

**Comment by continue-revolution** [comment]
> I'd like to write a feature to expose this model through the segment webui API. This would be pretty straightforward to accomplish but ideally, the endpoint would not accept dots as the prompt, but text. When do you think the integration with Grounded DINO would be completed? It's something I've worked on before so if you haven't started yet I could probably knock it out today.

GroundingDINO integration almost completed, near the end of debug. I will soon review your code and merge it. Do you want to write API with GroundingDINO enabled? If yes, please stay tuned

**Comment by jordan-barrett-jm** [comment]
Yep, would prefer Grounding DINO be enabled before starting on it. Will sit tight then

**Comment by continue-revolution** [comment]
GroundingDINO support done via merging #21
