### ISSUE TITLE
[Feature request]: Button to unload model 

### ISSUE THREAD

**Issue by specblades** [continue-revolution/sd-webui-segment-anything#17]
Add a button to unload model, please

**Comment by continue-revolution** [comment]
Move model from GPU to CPU or just remove it from whatever memory in your computer?

**Comment by specblades** [comment]
Just remove. For situations where we are no longer going to work with the extention.

**Comment by continue-revolution** [comment]
This feature has been added to #21 and will soon be merged to the master branch.

**Comment by continue-revolution** [comment]
Done via merging #21
