### ISSUE TITLE
[Bug]: not an issue question on densepose

### ISSUE THREAD

**Issue by johndpope** [continue-revolution/sd-webui-segment-anything#177]
@continue-revolution - is there a reason why there's no densepose for controlnet? seems superior option for body detection.

https://www.reddit.com/r/StableDiffusion/comments/17yirws/openpose_alternatives_humansd_densepose/

https://github.com/facebookresearch/detectron2/issues/5166

**Comment by continue-revolution** [comment]
I don't think it is something that is related to segment anything. You can try to post a feature request to https://github.com/Mikubill/sd-webui-controlnet
