### ISSUE TITLE
[Bug]: Mac M2 issue：mlir module expected element type f32 but received si32

### ISSUE THREAD

**Issue by TyroneZhang** [continue-revolution/sd-webui-segment-anything#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you updated WebUI and this extension to the newest version?

- [X] I have updated WebUI and this extension to the most up-to-date version

### What happened?

/AppleInternal/Library/BuildRoots/9e200cfa-7d96-11ed-886f-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphExecutable.mm:1309: failed assertion `Incompatible element type for parameter at index 0, mlir module expected element type f32 but received si32'

### Steps to reproduce the problem

1. add a black point
2. click “preview segmentation”

### What should have happened?

none

### Commit where the problem happens

webui: 
extension: 

### Command Line Arguments

```Shell
none
```

### Console logs

```Shell
/AppleInternal/Library/BuildRoots/9e200cfa-7d96-11ed-886f-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphExecutable.mm:1309: failed assertion `Incompatible element type for parameter at index 0, mlir module expected element type f32 but received si32'
```

**Comment by continue-revolution** [comment]
It seems that your error is similar to #16 but I do not have access to Mac. Would appreciate if anybody else could help.
