### ISSUE TITLE
[Bug]: What is https://star-history.com ?

### ISSUE THREAD

**Issue by ema7569** [continue-revolution/sd-webui-segment-anything#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you updated WebUI and this extension to the latest version?

- [X] I have updated WebUI and this extension to the latest version

### Do you understand that you should read the 1st item of https://github.com/continue-revolution/sd-webui-segment-anything#faq if you cannot install GroundingDINO?

- [X] My problem is not about installing GroundingDINO

### Do you understand that you should use the latest ControlNet extension and enable external control if you want SAM extension to control ControlNet?

- [X] I have updated ControlNet extension and enabled "Allow other script to control this extension"

### Do you understand that you should read the 2nd item of https://github.com/continue-revolution/sd-webui-segment-anything#faq if you observe problems like AttributeError bool object has no attribute enabled and TypeError bool object is not subscriptable?

- [X] My problem is not about such issue, otherwise I have tried changing the extension directory name from sd-webui-segment-anything to a1111-sd-webui-segment-anything

### What happened?

Hello, what the object of https://star-history.com ? I can't install ext that have connection to external sites

### Steps to reproduce the problem

.

### What should have happened?

.

### Commit where the problem happens

webui: 
extension: 

### Command Line Arguments

```Shell
.
```

### Console logs

```Shell
.
```

### Additional information

.

**Comment by continue-revolution** [comment]
it just displays the curve of my github star increase. you can safely ignore that
