### ISSUE TITLE
[Feature]: 能否添加一个给蒙版上色的功能

### ISSUE THREAD

**Issue by 54681** [continue-revolution/sd-webui-segment-anything#22]
这个插件很好用，但是在改变颜色的时候，尤其是要求指定一种颜色时，写tag的效果并不是那么有效果，想到之前的颜色蒙版，那是否可以添加这样一个功能，可以改变蒙版的颜色，做到类似之前颜色蒙版的效果。我对程序并不了解，所以不清楚这个功能是否能简单实现。最后，感谢大佬的插件。

**Comment by continue-revolution** [comment]
难度不大，我会在merge #21 之后尝试支持这个功能
