### ISSUE TITLE
[Bug]Batch没有考虑到处理目录下有文件夹的情况，报错

### ISSUE THREAD

**Issue by little-wheat** [continue-revolution/sd-webui-segment-anything#34]
在需要处理的目录下新建一个文件夹可以复现
![image](https://user-images.githubusercontent.com/11582918/232315888-102bd328-bbd4-4d13-a348-680f27a4167c.png)

**Comment by continue-revolution** [comment]
我目前没有打算处理文件夹，麻烦你不要在batch的文件夹目录里放别的文件夹。

**Comment by little-wheat** [comment]
ok
