### ISSUE TITLE
[Bug]在Batch处理下，GroundingDINO Box Threshold设置太大会导致报错

### ISSUE THREAD

**Issue by little-wheat** [continue-revolution/sd-webui-segment-anything#35]
在设置为0.4时不会报错，设置到0.5就会报错了，看起来是SAM报错，如果处理不了，希望可以跳过报错，继续处理下一张图片。
![image](https://user-images.githubusercontent.com/11582918/232316494-9264889c-e125-4ef6-98b6-799c116ded1d.png)

**Comment by continue-revolution** [comment]
报错是因为生成的box都被过滤掉了。等会会有一个更新处理这种情况。

**Comment by continue-revolution** [comment]
你的两个issue现在都已经支持了。
