### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'modules.paths_internal'

### ISSUE THREAD

**Issue by Zetaphor** [continue-revolution/sd-webui-segment-anything#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Error loading script: sam.py
Traceback (most recent call last):
  File "/home/zetaphor/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/home/zetaphor/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/zetaphor/stable-diffusion-webui/extensions/sd-webui-segment-anything/scripts/sam.py", line 10, in <module>
    from modules.paths_internal import extensions_dir
ModuleNotFoundError: No module named 'modules.paths_internal'

### Steps to reproduce the problem

1. Launch the webui
2. The script failes to initialize

### What should have happened?

The script should initialize

### Commit where the problem happens

webui: a9eab236d7e8afa4d6205127904a385b2c43bb24
controlnet: 187ae88038af6f4daa91d5dc941564d9a4df90ef

### Command Line Arguments

```Shell
--api --cors-allow-origins=* --opt-split-attention --upcast-sampling --precision autocast --opt-sdp-attention
```

### Console logs

```Shell
################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on zetaphor user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.9.16 (main, Mar  6 2023, 19:01:01) 
[GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
Commit hash: a9eab236d7e8afa4d6205127904a385b2c43bb24
Installing requirements for Web UI

Installing sd-dynamic-prompts requirements.txt




Launching Web UI with arguments: --api --cors-allow-origins=* --opt-split-attention --upcast-sampling --precision autocast --opt-sdp-attention
/home/zetaphor/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
No module 'xformers'. Proceeding without it.
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: /home/zetaphor/stable-diffusion-webui/extensions/Stable-Diffusion-Webui-Civitai-Helper/setting.json
Civitai Helper: No setting file, use default
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
Error loading script: sam.py
Traceback (most recent call last):
  File "/home/zetaphor/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/home/zetaphor/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/zetaphor/stable-diffusion-webui/extensions/sd-webui-segment-anything/scripts/sam.py", line 10, in <module>
    from modules.paths_internal import extensions_dir
ModuleNotFoundError: No module named 'modules.paths_internal'

Loading weights [26fc13daff] from /home/zetaphor/stable-diffusion-webui/models/Stable-diffusion/People/mishen-protogen34-5k-astria.ckpt
Creating model from config: /home/zetaphor/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: /home/zetaphor/stable-diffusion-webui/models/VAE/vae-ft-mse-840000-ema-pruned.safetensors
Applying scaled dot product cross attention optimization.
Model loaded in 4.6s (load weights from disk: 1.1s, create model: 0.4s, apply weights to model: 0.8s, apply half(): 0.5s, load VAE: 0.9s, move model to device: 0.5s, load textual inversion embeddings: 0.4s).
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 4 (delta 2), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (4/4), 906 bytes | 906.00 KiB/s, done.
From https://github.com/zero01101/openOutpaint
   64bc673..899c2cb  main       -> origin/main
Submodule path 'app': checked out '899c2cb59262c278314e87717ed01c566a4dd769'
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 14.5s (import gradio: 2.2s, import ldm: 0.6s, other imports: 0.9s, list extensions: 1.1s, load scripts: 1.8s, load SD checkpoint: 4.6s, create ui: 2.7s, gradio launch: 0.5s).
```

**Comment by continue-revolution** [comment]
You can either update your webui version or update this extension with `git pull`. The current version of this extension has gotten rid of `paths_internal`, which is a new feature of stable diffusion webui.

**Comment by Zetaphor** [comment]
Updating the extension fixed it, thanks!

Many of us are waiting to update our webui as the new version is still _very_ buggy. At first it broke a number of extensions (including my own) but that seems to have mostly settled. Now we're waiting for a number of the performance and gradio related bugs to be resolved before making the move permanently.

**Comment by Zetaphor** [comment]
Just went to try it out and it looks like I can't add the dots either.

Are you officially not supporting the pre-March 25'th version of the webui @continue-revolution?

If so you may want to add that to the documentation

**Comment by continue-revolution** [comment]
> Just went to try it out and it looks like I can't add the dots either.
> 
> Are you officially not supporting the pre-March 25'th version of the webui @continue-revolution?
> 
> If so you may want to add that to the documentation

Probably later but not my first priority, but I would prefer you to update the webui and all the extensions so that I can spend time on creating new features, while not delaying other stuff in my life. At least on my side, Lora and ControlNet have no problem using the current webui version. I will add a suggestion on the readme before I really have time to looking into it.
