### ISSUE TITLE
[Feature]: API endpoint for points?

### ISSUE THREAD

**Issue by aluhrs13** [continue-revolution/sd-webui-segment-anything#40]
Maybe I’m misunderstanding the API, but it seems like it only works with groundingDINO right now. 

Would it be possible to add a field to the API endpoint that takes in a series of points that are the equivalent of where you would click in the UI? Or maybe a mask of green and/or red that gets translated into include/exclude points?

**Comment by continue-revolution** [comment]
Yes, I have already discussed this with @jordan-barrett-jm . He is the main contributor of API and he has been helping me a lot while I’m working on other features. When he has time, he will improve API support.

**Comment by jordan-barrett-jm** [comment]
I can work on this soon @continue-revolution. I wanted to be clear though that the intended field would accept an array of tuples?

**Comment by continue-revolution** [comment]
In my code, it is two N*2 arrays. Not sure whether tuple can work.

**Comment by aluhrs13** [comment]
Awesome! From my perspective as the asker for this - I have two lists of X,Y coordinates. Translating that to some other structure to match the API shape probably shouldn’t be a problem.
