### ISSUE TITLE
是否存在和ControlNet的seg模式关联的可能性？

### ISSUE THREAD

**Issue by watersliang** [continue-revolution/sd-webui-segment-anything#41]
ControlNet的seg模式十分强大，可以用来控制构图和画面内容，但似乎controlNet使用的seg模型识别的颜色与语义的映射，与segment-anything不太一样。但segment-anything拥有更加强大的识别和分割能力。是否有这样的可能性：使用segment-anything分割和识别一张图片，并输出Controlnet的Seg模式能使用的图呢。

注：该问题可能问得非常的外行，属于处于直觉的一个疑问。

感谢大佬

**Comment by continue-revolution** [comment]
看看readme的plan你就知道了。

如果你不想看的话：很快就会支持。
