### ISSUE TITLE
[Bug]: User interface hangs when opening gradio accordion

### ISSUE THREAD

**Issue by ljleb** [continue-revolution/sd-webui-segment-anything#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

After a fresh install of the extension, it seems that I am unable to open the gradio accordion. The whole interface freezes when I click on it to open.

Tested both soft ui reload and hard restart, same result in both cases.

### Steps to reproduce the problem

1. Go to txt2img or img2img tab, both have the same behavior
2. Click on the accordion
3. Nothing happens, the cursor stays in "pointy" mode, and the ui is no more responsive.

### What should have happened?

The interface should not freeze when interacting with it.

### Commit where the problem happens

webui: 22bcc7be
sam: e93d178

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--api --api-log --allow-code
```

### Console logs

```Shell
none
```

### Additional information

The ui does not freeze in chrome. If anyone else has the same issue, try changing browser. I do not have any other extension than adblock. (which is disabled on localhost in my case)

**Comment by talzahr** [comment]
Same issue on Firefox. FF freaks out and says the page is slowing the browser. Did a fresh install via git clone and made sure the requirements.txt dep was installed in the venv. Switched to Edge and it worked well. 

No messages in the terminal.

**Comment by continue-revolution** [comment]
yes, you are right. I did not test on firefox after I merged a pull request. I will try to fix for firefox. Stay tuned.

**Comment by ljleb** [comment]
Can confirm [c27b078](https://github.com/continue-revolution/sd-webui-segment-anything/commit/c27b078e0521d71c3368e99bec1f9c2e362d5331) fixes the issue for me.
