### ISSUE TITLE
[Feature] Drop down menu for GroundingDINO?

### ISSUE THREAD

**Issue by AdrianTheFrog** [continue-revolution/sd-webui-segment-anything#50]
The segment anything menu now looks fairly cluttered, and there is a lot of unnecessary space taken up by GroundingDINO even when it is not being used. This could be solved by putting GroundingDINO inside of a drop down menu like what is done with the ControlNet canvas sliders.

**Comment by continue-revolution** [comment]
I am not sure which part is unnecessary when GroundingDINO is not enabled. When you uncheck "Enable GroundingDINO", everything about GroundingDINO should disappear, except that checkbox.
