### ISSUE TITLE
 can I set Dino to run using the CPU?

### ISSUE THREAD

**Issue by g558800** [continue-revolution/sd-webui-segment-anything#52]
How can I set Dino to run using the CPU? When running on the GPU, the error "NameError: name '_ C' is not defined" will appear.

**Comment by continue-revolution** [comment]
https://github.com/continue-revolution/sd-webui-segment-anything/issues/32#issuecomment-1513873296

Resolve _C problem according to the above issue.

**Comment by g558800** [comment]
Do I need to install VC++buildtools for this repo?

**Comment by continue-revolution** [comment]
I don't know. If the above step does not help, go to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues and submit an issue there

**Comment by YHD233** [comment]
Does ROCm not support it?
