### ISSUE TITLE
ERROR: Could not build wheels for groundingdino, pycocotools, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by bjsongzhen** [continue-revolution/sd-webui-segment-anything#53]
pycocotools\_mask.c(6): fatal error C1083: \xce޷\xa8\xb4򿪰\xfc\xc0\xa8\xceļ\xfe: \xa1\xb0Python.h\xa1\xb1: No such file or directory

      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

  ERROR: Failed building wheel for pycocotools

ERROR: Could not build wheels for groundingdino, pycocotools, which is required to install pyproject.toml-based projects

**Comment by continue-revolution** [comment]
Similar to #27 

You may either go to #27 and ask there how they solved the problem, or go to https://github.com/IDEA-Research/Grounded-Segment-Anything and submit the full exception there.

**Comment by wangfeng-1** [comment]
windows安装 vs_BuildTools ，https://visualstudio.microsoft.com/zh-hans/visual-cpp-build-tools/
