### ISSUE TITLE
怎么保存真正透明的png图片

### ISSUE THREAD

**Issue by w73w030** [continue-revolution/sd-webui-segment-anything#54]
segment计算后的mask结果，肉眼来看是一张背景完全透明的png图片
![image](https://user-images.githubusercontent.com/131244546/233284037-9088ab22-3a4f-4c5c-a345-41154b4578c8.png)
如果在PS里擦除多余选择的内容，放进img2img重绘后，会发现png变成了一张“图片”（这里是用Control net线稿看得比较清楚一点）
![企业微信截图_16819731489035](https://user-images.githubusercontent.com/131244546/233283027-073c3349-ec54-4cfe-89e4-9c2b573c0534.png)
而直接保存后未修改的png却不会（如图）
![image](https://user-images.githubusercontent.com/131244546/233283289-1a5c846c-2386-4947-bce7-16ef287f45ea.png)

segment计算后的结果并不一定完全准确，需要经过后期调整，有办法可以解决这个问题吗

**Comment by continue-revolution** [comment]
没懂你的意思，什么叫png变成了一张“图片”？

**Comment by w73w030** [comment]
> 

可以看第二张图，经过ps处理后，使用control net识别，这张png出现了边框，并且中间部分的内容有明显被裁剪的痕迹。
使用这张被处理过后的png进行图生图，也会自带一个和这个边框大小一致的黑色背景TUT

**Comment by w73w030** [comment]
> 你意思是如果你不往ps里放就没事，往ps里放就会出现边缘杂质吗？如果是的话这恐怕是一个玄学问题，我也没啥办法。如果不往ps里放也会出现边缘杂质，过两天的大更新的某一个feature可能可以处理这个问题（具体地说就是你自己再涂一遍，只有你涂了的地方才会有效）。

明白！感谢抽空回答！那接下来就等新的版本啦，大佬辛苦！！(￣▽￣* )ゞ
