### ISSUE TITLE
[Feature]: 希望把模型下载目录放到stable diffusion/models下面

### ISSUE THREAD

**Issue by sdbds** [continue-revolution/sd-webui-segment-anything#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you updated WebUI and this extension to the newest version?

- [X] I have updated WebUI and this extension to the most up-to-date version

### Do you understand that you should go to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues if you cannot install GroundingDINO?

- [X] My problem is not about installing GroundingDINO

### Do you know that you should use the newest ControlNet extension and enable external control if you want SAM extension to control ControlNet?

- [X] I have updated ControlNet extension and enabled "Allow other script to control this extension"

### What happened?

好几个插件都在用seg和dino...一个seg模型2.5G，连续下几个太麻烦了。
现在用软连接放各个插件里面，还是希望能像controlnet那样以后迁移到models文件夹下面。

### Steps to reproduce the problem

目录迁移

### What should have happened?

目录迁移

### Commit where the problem happens

目录迁移

### Command Line Arguments

```Shell
目录迁移
```

### Console logs

```Shell
目录迁移
```

**Comment by continue-revolution** [comment]
#20 已经解决SAM
#57 之后会把dino移动到models下

**Comment by continue-revolution** [comment]
而且很难支持你这个需求，如果有其他插件也在用sam和dino的话，现在并没有（也不可能有）一个统一的协议规定要放哪儿

**Comment by sdbds** [comment]
> 而且很难支持你这个需求，如果有其他插件也在用sam和dino的话，现在并没有（也不可能有）一个统一的协议规定要放哪儿

感谢，只能一个一个提了...现阶段是用软链接一个一个加。
