### ISSUE TITLE
[Bug]: Cannot View preview and cannot use it in img2img

### ISSUE THREAD

**Issue by GaryRandom** [continue-revolution/sd-webui-segment-anything#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I cannot add points by this extension in img2img, but can add points in txt2img. 
Then, when I click preview, it cannot show image and report error.

### Steps to reproduce the problem

1. start webui at a serve in the local network
2. access webui at a laptop in the local network
3. bug occurs

### What should have happened?

Successfully preview segmentation map

### Commit where the problem happens
[e93d178](https://github.com/continue-revolution/sd-webui-segment-anything/commit/e93d1780e8e7fd2edbfc6dfe0e29a7ee8efcc3f4)

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Traceback (most recent call last):
  File "xxx/stablediffusion/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "xxx/stablediffusion/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "xxx/stablediffusion/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range
```

**Comment by continue-revolution** [comment]
You should probably update your webui to the newest version.

**Comment by GaryRandom** [comment]
> You should probably update your webui to the newest version. What’s your version of webui?

a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
I will update and test again

**Comment by GaryRandom** [comment]
> > You should probably update your webui to the newest version. What’s your version of webui?
> 
> a9fed7c364061ae6efb37f797b6b522cb3cf7aa2 I will update and test again

Update to latest webui solve this problem

**Comment by zhongnannk** [comment]
File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1073, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 962, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/usr/local/lib/python3.9/dist-packages/gradio/components.py", line 1203, in preprocess
    return self.choices.index(x)

how to fix this problem?

**Comment by continue-revolution** [comment]
> File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 394, in run_predict output = await app.get_blocks().process_api( File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1073, in process_api inputs = self.preprocess_data(fn_index, inputs, state) File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 962, in preprocess_data processed_input.append(block.preprocess(inputs[i])) File "/usr/local/lib/python3.9/dist-packages/gradio/components.py", line 1203, in preprocess return self.choices.index(x)
> 
> how to fix this problem?

This is due to a bug inside grading. Could you provide me the steps to reproduce this error? I can reproduce this error and find a way to bypass this gradio bug.

**Comment by pggpeng** [comment]
> > File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 394, in run_predict output = await app.get_blocks().process_api( File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1073, in process_api inputs = self.preprocess_data(fn_index, inputs, state) File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 962, in preprocess_data processed_input.append(block.preprocess(inputs[i])) File "/usr/local/lib/python3.9/dist-packages/gradio/components.py", line 1203, in preprocess return self.choices.index(x)
> > how to fix this problem?
> 
> This is due to a bug inside gradio. Could you provide me the steps to reproduce this error? I can reproduce this error and find a way to bypass this gradio bug.

Same problem. If enable this extension, when i run txt2img or img2img, this problem occured. If disable this extension, everything is ok. My version: python: 3.10.9  •  torch: 2.0.0+cu117  •  xformers: 0.0.18  •  gradio: 3.23.0  •  commit: [22bcc7be](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81)

**Comment by continue-revolution** [comment]
https://github.com/continue-revolution/sd-webui-segment-anything/issues/49
