### ISSUE TITLE
Copy to inpaint upload doesn't work

### ISSUE THREAD

**Issue by baaoh** [continue-revolution/sd-webui-segment-anything#62]
hello! amazing extension, but for me when I tick the box "copy to inpaint upload" and then press "switch to Inpaint Upload", the mask does not transfer, and I have to do it manually.

**Comment by continue-revolution** [comment]
Can you record a video of the process you encountered this error and the complete terminal error? This will be extremely helpful for me to figure out the problem.

**Comment by chace20** [comment]
I also confused by this option.

When I review the code, I found the mask will be taken when draw in the background, but will not show in UI. 

![image](https://github.com/continue-revolution/sd-webui-segment-anything/assets/7760149/50eedc82-3f7f-4c11-b3bc-fc209c4f09ce)

https://github.com/continue-revolution/sd-webui-segment-anything/blob/7bd8b81e7d7dd745a5c0c59b6d190fcfc8cb0abc/scripts/process_params.py#L41

**Comment by continue-revolution** [comment]
You do not need to upload anything to the Inpaint upload panel. I do not want to copy the mask into the panel to actually let you see it. It is completely unnecessary.

**Comment by baaoh** [comment]
after updates/reading your comment, it works

**Comment by continue-revolution** [comment]
Yes, there is something wrong inside webui/ControlNet and I ended up bypassing this problem
