### ISSUE TITLE
Give indication that Switch to Inpaint Upload worked

### ISSUE THREAD

**Issue by pham-nhat-khanh** [continue-revolution/sd-webui-segment-anything#66]
I'm using sam to mask face + inpaint upload with loopback to fix faces like people suggested. I'm assuming that Switch to Inpaint Upload is working because it only changes the part that was masked ( like pic below ). 
There's no indicator that the inpaint is using your mask or not though. Can you update the Mask instead of leaving it blank and if not, some other form of indication.
Thanks for the hard work you've put on.
![github-issue-1](https://user-images.githubusercontent.com/24745349/234603634-48d6fa81-a8fa-4ae6-8a2f-9f9e9ae03581.png)
![github-issue-2](https://user-images.githubusercontent.com/24745349/234603632-c75b16d1-87ec-4ff8-89ee-44ffd4ed17b7.png)
![github-issue-3](https://user-images.githubusercontent.com/24745349/234603626-43839ea2-7101-45a0-a1c6-ce6493ab69ee.png)
![github-issue-4](https://user-images.githubusercontent.com/24745349/234603613-b22cb43f-a714-4f2c-9894-0a20ca64f908.png)
![github-issue-5](https://user-images.githubusercontent.com/24745349/234603622-375edccc-9111-4d23-a14f-40f2cb08ad5d.png)
(I clicked Switch to Inpaint Upload multiple times )

**Comment by continue-revolution** [comment]
When I used ControlNet inpainting on my device, I observed a masked image at the right hand side of the generated image. It should be your original image, with masked region blackened. That is the actual input of the ControlNet. You can check if that image exists, to see whether my extension is working.
