### ISSUE TITLE
秋叶整合版安装GroundingDINO安装时候报错

### ISSUE THREAD

**Issue by guytakeiteasy** [continue-revolution/sd-webui-segment-anything#67]
D:\tools\Stable diffusion\SD-webui-aki-v3\py310\lib\site-packages\torch\include\c10/util/Optional.h(554): note: \xb2鿴\xb6\xd4\xd5\xfd\xd4ڱ\xe0\xd2\xeb\xb5\xc4 \xb1\xf0\xc3\xfb ģ\xb0\xe5 ʵ\xc0\xfd\xbb\xaf\xa1\xb0c10::OptionalBase<T>\xa1\xb1\xb5\xc4\xd2\xfd\xd3\xc3

              with

              [

                  T=std::vector<at::Tensor,std::allocator<at::Tensor>>

              ]

      D:\tools\Stable diffusion\SD-webui-aki-v3\py310\lib\site-packages\torch\include\torch\csrc\api\include\torch/optim/lbfgs.h(50): note: \xb2鿴\xb6\xd4\xd5\xfd\xd4ڱ\xe0\xd2\xeb\xb5\xc4 \xc0\xe0 ģ\xb0\xe5 ʵ\xc0\xfd\xbb\xaf\xa1\xb0c10::optional<std::vector<at::Tensor,std::allocator<at::Tensor>>>\xa1\xb1\xb5\xc4\xd2\xfd\xd3\xc3

      D:\tools\Stable diffusion\SD-webui-aki-v3\py310\lib\site-packages\torch\include\c10/util/Optional.h(446): warning C4624: \xa1\xb0c10::trivially_copyable_optimization_optional_base<T>\xa1\xb1: \xd2ѽ\xab\xce\xf6\xb9\xb9\xba\xaf\xca\xfd\xd2\xfeʽ\xb6\xa8\xd2\xe5Ϊ\xa1\xb0\xd2\xd1ɾ\xb3\xfd\xa1\xb1

              with

              [

                  T=std::vector<at::Tensor,std::allocator<at::Tensor>>

              ]

      D:\tools\Stable diffusion\SD-webui-aki-v3\py310\lib\site-packages\torch\include\torch/csrc/python_headers.h(12): fatal error C1083: \xce޷\xa8\xb4򿪰\xfc\xc0\xa8\xceļ\xfe: \xa1\xb0Python.h\xa1\xb1: No such file or directory

      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

  ERROR: Failed building wheel for groundingdino

  error: subprocess-exited-with-error

  × Building wheel for pycocotools (pyproject.toml) did not run successfully.

  │ exit code: 1

  ╰─> [23 lines of output]

      running bdist_wheel

      running build

      running build_py

      creating build

      creating build\lib.win-amd64-cpython-310

      creating build\lib.win-amd64-cpython-310\pycocotools

      copying pycocotools\coco.py -> build\lib.win-amd64-cpython-310\pycocotools

      copying pycocotools\cocoeval.py -> build\lib.win-amd64-cpython-310\pycocotools

      copying pycocotools\mask.py -> build\lib.win-amd64-cpython-310\pycocotools

      copying pycocotools\__init__.py -> build\lib.win-amd64-cpython-310\pycocotools

      running build_ext

      building 'pycocotools._mask' extension

      creating build\temp.win-amd64-cpython-310

      creating build\temp.win-amd64-cpython-310\Release

      creating build\temp.win-amd64-cpython-310\Release\common

      creating build\temp.win-amd64-cpython-310\Release\pycocotools

      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD "-ID:\tools\Stable diffusion\SD-webui-aki-v3\py310\lib\site-packages\numpy\core\include" -I./common "-ID:\tools\Stable diffusion\SD-webui-aki-v3\py310\include" "-ID:\tools\Stable diffusion\SD-webui-aki-v3\py310\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tc./common/maskApi.c /Fobuild\temp.win-amd64-cpython-310\Release\./common/maskApi.obj

      maskApi.c

      ./common/maskApi.c(151): warning C4101: \xa1\xb0xp\xa1\xb1: δ\xd2\xfd\xd3õľֲ\xbf\xb1\xe4\xc1\xbf

None
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD "-ID:\tools\Stable diffusion\SD-webui-aki-v3\py310\lib\site-packages\numpy\core\include" -I./common "-ID:\tools\Stable diffusion\SD-webui-aki-v3\py310\include" "-ID:\tools\Stable diffusion\SD-webui-aki-v3\py310\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-cpython-310\Release\pycocotools/_mask.obj
GroundingDINO install failed. Please submit an issue to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues.

      _mask.c

      c1: fatal error C1083: \xce޷\xa8\xb4\xf2\xbf\xaaԴ\xceļ\xfe: \xa1\xb0pycocotools/_mask.c\xa1\xb1: No such file or directory

      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

  ERROR: Failed building wheel for pycocotools

ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects

求助，有人知道错在哪里，该怎么弄么？

**Comment by continue-revolution** [comment]
去你发的报错里面的一个超链接那里提issue

**Comment by guytakeiteasy** [comment]
> 去你发的报错里面的一个超链接那里提issue

好的，谢谢，大佬，还有个问题想请教下，我安装完controlNet插件后，没有找到[inpaint_global_harmonious]这个预处理器,但是后面的模型列表里有control_v11p_sd15_inpaint [ebff9138]，这个是还需要安装什么吗？

**Comment by Jackylee2032** [comment]
除了上面那个错，我还报了一大堆这样的错，请问是为什么呢



checkpoint: 9.1s, create ui: 2.8s, gradio launch: 0.2s).
Installing sd-webui-segment-anything requirement: groundingdino
提示：SD-WebUI 正在联网同步内部组件，这可能需要几秒到几十分钟不等，请耐心等待，切勿中途退出，以免文件损坏。切换版本后在此挂起一段时间是正常情况，如果您在使用中反复需要在此处等待 5 分钟以上，这可能是由于您安装的扩展与主环境产生版本冲突。请尝试通过扩展管理工具手动对齐扩展版本，或停用可疑扩展。
详见: https://support.qq.com/products/488228/faqs/135024
              with

              [

                  T=c10::DimVector

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(549): note: 查看对正在编译的 别名 模板 实例化“c10::OptionalBase<T>”的引用

              with

              [

                  T=c10::DimVector

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\ATen/TensorIterator.h(918): note: 查看对正在编译的 类 模板 实例化“c10::optional<c10::DimVector>”的引用

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(446): warning C4624: “c10::trivially_copyable_optimization_optional_base<T>”: 已将析构函数隐式定义为“已删除”

              with

              [

                  T=c10::DimVector

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(212): warning C4624: “c10::constexpr_storage_t<T>”: 已将析构函数隐式定义为“已删除”

              with

              [

                  T=c10::impl::AnnotatedSchema

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(411): note: 查看对正在编译的 类 模板 实例化“c10::constexpr_storage_t<T>”的引用

              with

              [

                  T=c10::impl::AnnotatedSchema

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(549): note: 查看对正在编译的 类 模板 实例化“c10::trivially_copyable_optimization_optional_base<T>”的引用

              with

              [

                  T=c10::impl::AnnotatedSchema

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(549): note: 查看对正在编译的 别名 模板 实例化“c10::OptionalBase<T>”的引用

              with

              [

                  T=c10::impl::AnnotatedSchema

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\ATen/core/dispatch/OperatorEntry.h(223): note: 查看对正在编译的 类 模板 实例化“c10::optional<c10::impl::AnnotatedSchema>”的引用

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(446): warning C4624: “c10::trivially_copyable_optimization_optional_base<T>”: 已将析构函数隐式定义为“已删除”

              with

              [

                  T=c10::impl::AnnotatedSchema

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(212): warning C4624: “c10::constexpr_storage_t<T>”: 已将析构函数隐式定义为“已删除”

              with

              [

                  T=c10::impl::OperatorEntry::CppSignatureWithDebug

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(411): note: 查看对正在编译的 类 模板 实例化“c10::constexpr_storage_t<T>”的引用

              with

              [

                  T=c10::impl::OperatorEntry::CppSignatureWithDebug

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(549): note: 查看对正在编译的 类 模板 实例化“c10::trivially_copyable_optimization_optional_base<T>”的引用

              with

              [

                  T=c10::impl::OperatorEntry::CppSignatureWithDebug

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(549): note: 查看对正在编译的 别名 模板 实例化“c10::OptionalBase<T>”的引用

              with

              [

                  T=c10::impl::OperatorEntry::CppSignatureWithDebug

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\ATen/core/dispatch/OperatorEntry.h(286): note: 查看对正在编译的 类 模板 实例化“c10::optional<c10::impl::OperatorEntry::CppSignatureWithDebug>”的引用

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(446): warning C4624: “c10::trivially_copyable_optimization_optional_base<T>”: 已将析构函数隐式定义为“已删除”

              with

              [

                  T=c10::impl::OperatorEntry::CppSignatureWithDebug

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(212): warning C4624: “c10::constexpr_storage_t<T>”: 已将析构函数隐式定义为“已删除”

              with

              [

                  T=std::tuple<std::string,size_t,size_t>

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(411): note: 查看对正在编译的 类 模板 实例化“c10::constexpr_storage_t<T>”的引用

              with

              [

                  T=std::tuple<std::string,size_t,size_t>

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(549): note: 查看对正在编译的 类 模板 实例化“c10::trivially_copyable_optimization_optional_base<T>”的引用

              with

              [

                  T=std::tuple<std::string,size_t,size_t>

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(549): note: 查看对正在编译的 别名 模板 实例化“c10::OptionalBase<T>”的引用

              with

              [

                  T=std::tuple<std::string,size_t,size_t>

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\torch/csrc/jit/frontend/source_range.h(357): note: 查看对正在编译的 类 模板 实例化“c10::optional<std::tuple<std::string,size_t,size_t>>”的引用

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(446): warning C4624: “c10::trivially_copyable_optimization_optional_base<T>”: 已将析构函数隐式定义为“已删除”

              with

              [

                  T=std::tuple<std::string,size_t,size_t>

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(212): warning C4624: “c10::constexpr_storage_t<T>”: 已将析构函数隐式定义为“已删除”

              with

              [

                  T=torch::jit::SourceRange

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(411): note: 查看对正在编译的 类 模板 实例化“c10::constexpr_storage_t<T>”的引用

              with

              [

                  T=torch::jit::SourceRange

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(549): note: 查看对正在编译的 类 模板 实例化“c10::trivially_copyable_optimization_optional_base<T>”的引用

              with

              [

                  T=torch::jit::SourceRange

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(549): note: 查看对正在编译的 别名 模板 实例化“c10::OptionalBase<T>”的引用

              with

              [

                  T=torch::jit::SourceRange

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\torch/csrc/jit/frontend/source_range.h(380): note: 查看对正在编译的 类 模板 实例化“c10::optional<torch::jit::SourceRange>”的引用

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(446): warning C4624: “c10::trivially_copyable_optimization_optional_base<T>”: 已将析构函数隐式定义为“已删除”

              with

              [

                  T=torch::jit::SourceRange

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(212): warning C4624: “c10::constexpr_storage_t<T>”: 已将析构函数隐式定义为“已删除”

              with

              [

                  T=torch::jit::InlinedCallStackPtr

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(411): note: 查看对正在编译的 类 模板 实例化“c10::constexpr_storage_t<T>”的引用

              with

              [

                  T=torch::jit::InlinedCallStackPtr

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(549): note: 查看对正在编译的 类 模板 实例化“c10::trivially_copyable_optimization_optional_base<T>”的引用

              with

              [

                  T=torch::jit::InlinedCallStackPtr

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(549): note: 查看对正在编译的 别名 模板 实例化“c10::OptionalBase<T>”的引用

              with

              [

                  T=torch::jit::InlinedCallStackPtr

              ]

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\torch/csrc/jit/ir/scope.h(127): note: 查看对正在编译的 类 模板 实例化“c10::optional<torch::jit::InlinedCallStackPtr>”的引用

      D:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\include\c10/util/Optional.h(446): warning C4624: “c10::trivially_copyable_optimization_optional_base<T>”: 已将析构函数隐式定义为“已删除”

              with

**Comment by cdmusic2019** [comment]
使用整合版的小伙伴们，也许是因为从github（本站）更新资源有问题才使用的，一般需要先解决这个问题才能正常更新。我没有用使用整合版，用的官方原版，但开始从github更新资源时，发现访问正常，但是更新不了，是因为我们DNS被污染了。所以需要先在CMD中重置代理方式。

**Comment by Jackylee2032** [comment]
具体怎么操作呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月29日(周六) 上午10:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [continue-revolution/sd-webui-segment-anything] 秋叶整合版安装GroundingDINO安装时候报错 (Issue #67)




 
使用整合版的小伙伴们，也许是因为从github（本站）更新资源有问题才使用的，一般需要先解决这个问题才能正常更新。我没有用使用整合版，用的官方原版，但开始从github更新资源时，发现访问正常，但是更新不了，是因为我们DNS被污染了。所以需要先在CMD中重置代理方式。

**Comment by guytakeiteasy** [comment]
> 使用整合版的小伙伴们，也许是因为从github（本站）更新资源有问题才使用的，一般需要先解决这个问题才能正常更新。我没有用使用整合版，用的官方原版，但开始从github更新资源时，发现访问正常，但是更新不了，是因为我们DNS被污染了。所以需要先在CMD中重置代理方式。

我看了下，在秋叶V3一键整合包里面，它默认设置替换成了国产的镜像地址，我本地试了，不管是原来的git地址还是镜像的git地址都是可以访问的，不知道这个会不会存在更新不及时的问题，但是我直接从原来的git链接直接下载zip然后解压后放到extensions下面貌似也会现同样的问题。
![image](https://user-images.githubusercontent.com/28588238/235285288-4c92cd18-0cbb-4854-ad05-fd1e9fa2ce93.png)
![image](https://user-images.githubusercontent.com/28588238/235285330-36eacb96-d42c-4e62-a06c-356d271bb7c7.png)

**Comment by cdmusic2019** [comment]
@guytakeiteasy,多多少少跟整合版有点关系，因为我不用整合版，https://github.com/Mikubill/sd-webui-controlnet，这个贴子中有一段话“If your A1111 Extension's ControlNet displays a link look like 'jihulab.com/affair3547', then unfortunately, your A1111 does NOT support ControlNet 1.1. Please use official version of A1111.”，这可能就是整合版或使使用第三方的版本，所以会不兼容。

**Comment by YanXiaoAI** [comment]
同样的问题，秋叶整合包，所以大家都解决了么？

**Comment by xuewen45** [comment]
Installing sd-webui-segment-anything requirement: groundingdino
提示：SD-WebUI 正在联网同步内部组件，这可能需要几秒到几十分钟不等，请耐心等待，切勿中途退出，以免文件损坏。切换版本后在此挂起一段时间是正常情况，如果您在使用中反复需要在此处等待 5 分钟以上，这可能是由于您安装的扩展与主环境产生版本冲突。请尝试通过扩展管理工具手动对齐扩展版本，或停用可疑扩展。
详见: https://support.qq.com/products/488228/faqs/135024
Traceback (most recent call last):
GroundingDINO install failed. Will fall back to local groundingdino this time. Please permanently switch to local groundingdino on Settings/Segment Anything or submit an issue to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues.
  File "E:\Stable Diffusion\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\dino.py", line 67, in install_goundingdino
Running GroundingDINO Inference
    launch.run_pip(
  File "E:\Stable Diffusion\sd-webui-aki-v4\launch.py", line 129, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "E:\Stable Diffusion\sd-webui-aki-v4\launch.py", line 97, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install sd-webui-segment-anything requirement: groundingdino.
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Command: "E:\Stable Diffusion\sd-webui-aki-v4\py310\python.exe" -m pip install git+https://github.com/IDEA-Research/GroundingDINO --prefer-binary --index-url https://mirror.baidu.com/pypi/simple
Error code: 1
stdout: Looking in indexes: https://mirror.baidu.com/pypi/simple, https://mirrors.aliyun.com/pypi/simple

Looking in links: https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html

Collecting git+https://github.com/IDEA-Research/GroundingDINO

  Cloning https://github.com/IDEA-Research/GroundingDINO to c:\users\administrator\appdata\local\temp\pip-req-build-w6d24dcs

stderr:   Running command git clone --filter=blob:none --quiet https://github.com/IDEA-Research/GroundingDINO 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-w6d24dcs'

  fatal: unable to access 'https://github.com/IDEA-Research/GroundingDINO/': Recv failure: Connection was reset

  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/IDEA-Research/GroundingDINO 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-w6d24dcs' did not run successfully.

  │ exit code: 128

  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.

error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/IDEA-Research/GroundingDINO 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-w6d24dcs' did not run successfully.

│ exit code: 128

╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Initializing GroundingDINO GroundingDINO_SwinB (938MB)
final text_encoder_type: bert-base-uncased

Traceback (most recent call last):
  File "E:\Stable Diffusion\sd-webui-aki-v4\py310\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "E:\Stable Diffusion\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\Stable Diffusion\sd-webui-aki-v4\py310\lib\site-packages\huggingface_hub\file_download.py", line 1259, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Stable Diffusion\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Stable Diffusion\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "E:\Stable Diffusion\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Stable Diffusion\sd-webui-aki-v4\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Stable Diffusion\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\Stable Diffusion\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\Stable Diffusion\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\sam.py", line 200, in sam_predict
    boxes_filt, install_success = dino_predict_internal(input_image, dino_model_name, text_prompt, box_threshold)
  File "E:\Stable Diffusion\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\dino.py", line 173, in dino_predict_internal
    dino_model = load_dino_model(dino_model_name, install_success)
  File "E:\Stable Diffusion\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\dino.py", line 119, in load_dino_model
    dino = build_model(args)
  File "E:\Stable Diffusion\sd-webui-aki-v4\extensions\sd-webui-segment-anything\local_groundingdino\models\__init__.py", line 17, in build_model
    model = build_func(args)
  File "E:\Stable Diffusion\sd-webui-aki-v4\extensions\sd-webui-segment-anything\local_groundingdino\models\GroundingDINO\groundingdino.py", line 362, in build_groundingdino
    model = GroundingDINO(
  File "E:\Stable Diffusion\sd-webui-aki-v4\extensions\sd-webui-segment-anything\local_groundingdino\models\GroundingDINO\groundingdino.py", line 97, in __init__
    self.tokenizer = get_tokenlizer.get_tokenlizer(text_encoder_type)
  File "E:\Stable Diffusion\sd-webui-aki-v4\extensions\sd-webui-segment-anything\local_groundingdino\util\get_tokenlizer.py", line 19, in get_tokenlizer
    tokenizer = AutoTokenizer.from_pretrained(text_encoder_type)
  File "E:\Stable Diffusion\sd-webui-aki-v4\py310\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 597, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "E:\Stable Diffusion\sd-webui-aki-v4\py310\lib\site-packages\transformers\models\auto\configuration_auto.py", line 809, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "E:\Stable Diffusion\sd-webui-aki-v4\py310\lib\site-packages\transformers\configuration_utils.py", line 559, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "E:\Stable Diffusion\sd-webui-aki-v4\py310\lib\site-packages\transformers\configuration_utils.py", line 614, in _get_config_dict
    resolved_config_file = cached_file(
  File "E:\Stable Diffusion\sd-webui-aki-v4\py310\lib\site-packages\transformers\utils\hub.py", line 443, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like bert-base-uncased is not the path to a directory containing a file named config.json.
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
为啥我抛出的异常是这个？要怎么解决？大佬？

**Comment by continue-revolution** [comment]
github和huggingface终端被墙，请自行配制终端代理。
