### ISSUE TITLE
关于 ade20k 和 coco 的类别ID？求助

### ISSUE THREAD

**Issue by FayeValentineR** [continue-revolution/sd-webui-segment-anything#79]
在用SAM批量处理的时候填入 ade20k 和 coco 的类别id但是得到的只是一张原图，一张黑图，一张透明图，我在插件上方注释处的文档链接里找到ade20k关于衣服的 {"color": [0, 112, 255], "id": 92, "isthing": 1, "name": "clothes"},我填入的id是92，是我的食用方式不对吗？抱歉我不懂

**Comment by continue-revolution** [comment]
你用ControlNet的preprocessor跑一下看看衣服的区域是不是这个颜色，如果不是，就没有办法。
语义分割只能加强controlnet的细节（尤其是边缘），因为sam本身不是语义分割，所以可能会受到语义分割模型的限制

**Comment by FayeValentineR** [comment]
这个color": [0, 112, 255]是指的RGB中的蓝色吗，我用ControlNet的三个语义分割预处理预览结果都是人物包括衣服为红色，是不是就是只能读取到颜色对应的ID....

**Comment by continue-revolution** [comment]
对的，这说明目前的语义分割还不具备识别某些衣服的能力。

**Comment by FayeValentineR** [comment]
> 对的，这说明目前的语义分割还不具备识别某些衣服的能力。

好的，谢谢大佬，这下明白了
