### ISSUE TITLE
HWC3 ImportError: cannot import name 'resize_image' from 'annotator.util'

### ISSUE THREAD

**Issue by daizhuo** [continue-revolution/sd-webui-segment-anything#87]
运行AutoSAM中，

先是下面这个错误

 os.symlink(cnet_annotator_dir, sam_annotator_dir, target_is_directory=True)
OSError: [WinError 1314] A required privilege is not held by the client: 'D:\\AI\\stable-diffusion-webui-1.1.0\\extensions\\sd-webui-controlnet/annotator' -> 'D:\\AI\\stable-diffusion-webui-1.1.0\\extensions\\sd-webui-segment-anything\\annotator'

然后我直接在插件里面创建了“annotator”这个文件夹

之后再报错：

 from annotator.util import resize_image, HWC3
ImportError: cannot import name 'resize_image' from 'annotator.util' (D:\AI\stable-diffusion-webui-1.1.0\extensions\sd-webui-controlnet\annotator\util.py)

我已经装了最新版的 controlnet，还是运行不了 AutoSAM，是不是BUG？

**Comment by continue-revolution** [comment]
这是因为controlnet更新之后把resize_img移除了。我这两天会更新一下这个。

**Comment by daizhuo** [comment]
感谢啊！

**Comment by continue-revolution** [comment]
https://github.com/continue-revolution/sd-webui-segment-anything/commit/a4b249114eb4f55809053ef80620c688de8e6ba3
