### ISSUE TITLE
AutoSAM 运算完后，不会把 seg 自动发到 controlnet

### ISSUE THREAD

**Issue by daizhuo** [continue-revolution/sd-webui-segment-anything#89]
感谢更新，终于可以用了！！！
但是有个小 Bug，即使勾选了Copy to ControlNet Segmentation，它也不会发送过去。
还得手动复制图片过去，有少少麻烦，烦请修正这个 Bug，谢谢！

另外，ControlNet Segmentation Index 永远只显示一个 0 的选项，我见你教程应该是 0，1，2三个选项，也是 Bug?

**Comment by continue-revolution** [comment]
我这里不需要手动复制，你发一下报错。

你没有启动multi-controlnet就只有1个

**Comment by Xav1erS** [comment]
> rolNet勾选允许其他插件控制这个拓展插件/Allow other script to control this extensi
同样的问题，设置过了还是发送不过去
