### ISSUE TITLE
[Bug]: 鼠标左键和右键点击了没有效果，环境为windows，浏览器为edge

### ISSUE THREAD

**Issue by smartOf360** [continue-revolution/sd-webui-segment-anything#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

在图生图中，使用Segment Anything中，鼠标左键和鼠标右击点击了完全没有反应，环境为windows，浏览器为edge

### Steps to reproduce the problem

在图生图中，使用Segment Anything中，鼠标左键和鼠标右击点击了完全没有反应，环境为windows，浏览器为edge

### What should have happened?

在图生图中，使用Segment Anything中，鼠标左键和鼠标右击点击了完全没有反应，环境为windows，浏览器为edge

### Commit where the problem happens

webui: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
controlnet: 603449ce (Fri Mar 31 19:07:44 2023)
其他:
python: 3.10.7  •  
torch: 2.0.0+cu118  •  
xformers: 0.0.17rc482  •  
gradio: 3.16.2  • 
commit: [a9fed7c3](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a9fed7c364061ae6efb37f797b6b522cb3cf7aa2)  • 

在图生图中，使用Segment Anything中，鼠标左键和鼠标右击点击了完全没有反应，环境为windows，浏览器为edge

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
no
```

**Comment by continue-revolution** [comment]
#5

**Comment by continue-revolution** [comment]
#6

**Comment by liulanghan8023** [comment]
我也遇到了

**Comment by continue-revolution** [comment]
> 我也遇到了

更新到最新版就能用

**Comment by CNMagicturtle** [comment]
same problem,same version,but i dont want to update my webui.dat.
python: 3.10.8  •  torch: 2.0.0+cu118  •  xformers: 0.0.17rc482  •  gradio: 3.16.2  •

**Comment by vikiiing** [comment]
webui3.14稳定版本同样问题，webui更新最新版本不稳定会遇到其他问题，能否进行优化

**Comment by continue-revolution** [comment]
我使用最新版没有遇到过问题。老版本需要等我把新feature弄好了我才有空看，可能需要等一段时间。建议先更新

**Comment by hanhongyi** [comment]
> 我使用最新版没有遇到过问题。老版本需要等我把新feature弄好了我才有空看，可能需要等一段时间。建议先更新

js里面有两个sam_input_image, 我这也有这个问题.

fix:
[sam.zip](https://github.com/continue-revolution/sd-webui-segment-anything/files/11221514/sam.zip)

**Comment by hanhongyi** [comment]
> 
js是因为有两个sam_input_image, 可以用下面这个fix.但是fix后会遇到 https://github.com/continue-revolution/sd-webui-segment-anything/issues/6  "list index out of range "这个问题... 

fix:
[sam.zip](https://github.com/continue-revolution/sd-webui-segment-anything/files/11222529/sam.zip)

**Comment by continue-revolution** [comment]
> > 
> 
> js是因为有两个sam_input_image, 可以用下面这个fix.但是fix后会遇到 #6 "list index out of range "这个问题...
> 
> fix: [sam.zip](https://github.com/continue-revolution/sd-webui-segment-anything/files/11222529/sam.zip)

提交pull request。你发压缩包我不好对比。
