### ISSUE TITLE
[Bug]: AttributeError: 'NoneType' object has no attribute 'mode'

### ISSUE THREAD

**Issue by jaksonlin** [continue-revolution/sd-webui-segment-anything#94]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you updated WebUI and this extension to the newest version?

- [X] I have updated WebUI and this extension to the most up-to-date version

### Do you understand that you should go to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues if you cannot install GroundingDINO?

- [X] My problem is not about installing GroundingDINO

### Do you know that you should use the newest ControlNet extension and enable external control if you want SAM extension to control ControlNet?

- [X] I have updated ControlNet extension and enabled "Allow other script to control this extension"

### What happened?

Hit exception during img2img inpainting

### Steps to reproduce the problem

1. segment the image with GroundingDINO enabled
2. Click `Preview Segment`
3. Check `Copy to ControlNet Inpainting`
4. Check `Expand Mask`
5. Set `Specify the amount that you wish to expand the mask` to 30
6. Click `Update Mask`
7. Click `Switch to inpaint Upload`
8. Mask mode set to `Inpaint not masked`
9. Click `Generate`

### What should have happened?

inpaint start correctly without exception

### Commit where the problem happens

webui: 
extension: 
python: 3.10.6  •  torch: 2.0.0+cu118  •  xformers: N/A  •  gradio: 3.28.1  •  commit: [5ab7f213](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ab7f213bec2f816f9c5644becb32eb72c8ffb89)  •  checkpoint: [fc2511737a](https://google.com/search?q=fc2511737a54c5e80b89ab03e0ab4b98d051ab187f92860f3cd664dc9d08b271)

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
NO
```

### Console logs

```Shell
Traceback (most recent call last):
  File "C:\Users\zhisl\stable-diffusion-webui-ok\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\zhisl\stable-diffusion-webui-ok\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\zhisl\stable-diffusion-webui-ok\modules\img2img.py", line 181, in img2img
    processed = process_images(p)
  File "C:\Users\zhisl\stable-diffusion-webui-ok\modules\processing.py", line 515, in process_images
    res = process_images_inner(p)
  File "C:\Users\zhisl\stable-diffusion-webui-ok\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "C:\Users\zhisl\stable-diffusion-webui-ok\modules\processing.py", line 604, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "C:\Users\zhisl\stable-diffusion-webui-ok\modules\processing.py", line 1038, in init
    image = images.flatten(img, opts.img2img_background_color)
  File "C:\Users\zhisl\stable-diffusion-webui-ok\modules\images.py", line 697, in flatten
    if img.mode == "RGBA":
AttributeError: 'NoneType' object has no attribute 'mode'
```

### Additional information

Truning on PDB to see the runtime values of the args in the trouble, It seems that the args passed into line `sd-webui-segment-anything\scripts\process_params.py(26)__init__()` does not fit in to the type you described in the __init__ function, please let me know if you need more args/stacktrace lookup.

Creating output image
> c:\users\zhisl\stable-diffusion-webui-ok\extensions\sd-webui-segment-anything\scripts\process_params.py(26)__init__()
-> self.init_sam_single_image_process(args)
(Pdb) pp args
(<controlnet.py.UiControlNetUnit object at 0x0000018F2885D150>,
 <controlnet.py.UiControlNetUnit object at 0x0000018F2DE73010>,
 <controlnet.py.UiControlNetUnit object at 0x0000018F2885C3A0>,
 False,
 False,
 'Horizontal',
 '1,1',
 '0.2')
(Pdb) ll
 14         def __init__(self, args: Tuple, is_img2img=False):
 15             self.is_img2img = is_img2img
 16
 17             self.inpaint_upload_enable: bool = False
 18             self.cnet_inpaint_invert: bool = False
 19             self.cnet_inpaint_idx: int = 0
 20             self.input_image = None
 21             self.output_mask_gallery: List[Dict] = None
 22             self.output_chosen_mask: int = 0
 23             self.dilation_checkbox: bool = False
 24             self.dilation_output_gallery: List[Dict] = None
 25             pdb.set_trace()
 26  ->         self.init_sam_single_image_process(args)
(Pdb) c

**Comment by jaksonlin** [comment]
attached the process arguments

> c:\users\zhisl\stable-diffusion-webui-ok\modules\scripts.py(417)process()
-> script.process(p, *script_args)
(Pdb) p script_args
(<controlnet.py.UiControlNetUnit object at 0x0000018F3BFB9750>, <controlnet.py.UiControlNetUnit object at 0x0000018F2CF82140>, <controlnet.py.UiControlNetUnit object at 0x0000018F2CF81780>, False, False, 'Horizontal', '1,1', '0.2', False, False, False, 'Attention', False, '0', '0', '0.4', None, False, False, 0)
(Pdb)

**Comment by continue-revolution** [comment]
will try to resolve in #93

**Comment by continue-revolution** [comment]
Your problem seems to be different. You need to be inside img2img to generate preview in order to make Sam effective. It seems that you generated preview inside txt2img then switched to img2img. I’m this way nothing can be uploaded to img2img.

**Comment by XiaoCC** [comment]
我也遇到相同的问题 你禁用一下sd-webui-mov2mov | https://ghproxy.com/https://github.com/Scholar01/sd-webui-mov2mov
这个插件试试看，我自己禁用了这个插件后就能正常发送到蒙板了。
作者可以兼容一下sd-webui-mov2mov么，谢谢

**Comment by XiaoCC** [comment]
我也遇到相同的问题 你禁用一下sd-webui-mov2mov | https://ghproxy.com/https://github.com/Scholar01/sd-webui-mov2mov
这个插件试试看，我自己禁用了这个插件后就能正常发送到蒙板了。
作者可以兼容一下sd-webui-mov2mov么，谢谢

**Comment by amimi818** [comment]
> Your problem seems to be different. You need to be inside img2img to generate preview in order to make Sam effective. It seems that you generated preview inside txt2img then switched to img2img. In this way nothing can be uploaded to img2img.

I had the same problem （the same steps as @jaksonlin ) , and I generated preview inside img2img(not txt2img).  So, that's not the reason for the problem.

**Comment by continue-revolution** [comment]
I am not able to reproduce your problem. The problem might come from some other extensions. A known extension that is not compatible with Sam is https://github.com/Scholar01/sd-webui-mov2mov

**Comment by jaksonlin** [comment]
findings:
1. disabling the mov2mov still fails. 
2. using SAM in the img2img is ok. (so why it would appear in t2i ? as it won't work anyway when clicking `switch to inpaint upload`

**Comment by continue-revolution** [comment]
> 1. disabling the mov2mov still fails.
This seems contradictory to 2. Do you mean that sam still fails in txt2img? If so, please provide terminal log.
> 2. using SAM in the img2img is ok. (so why it would appear in t2i ? as it won't work anyway when clicking `switch to inpaint upload`
Because ControlNet can inpaint in txt2img. Previously Sam only appears in img2img.

**Comment by amimi818** [comment]
I found the reason：If  "Expand Mask" be checked, the 'NoneType' object has no attribute 'mode'" error is generated, otherwise it is OK.

**Comment by continue-revolution** [comment]
> I found the reason：If "Expand Mask" be checked, the 'NoneType' object has no attribute 'mode'" error is generated, otherwise it is OK.

Thank you. I rarely use that feature. Will look into the reason after my vacation.

**Comment by jaksonlin** [comment]
> 

reviewing the code, it seems that `switch to inpaint upload` ui control not have any logic to pass result from t2i to i2i context.

**Comment by XiaoCC** [comment]
我用秋叶的包    只要启用了sd-webui-mov2mov 插件， 百分百AttributeError: 'NoneType' object has no attribute 'mode'，可以复现，希望能兼容一下

**Comment by continue-revolution** [comment]
@XiaoCC 你能不能试试看把我插件文件夹名前面加个a1111，我现在手头上没电脑，如果这么操作可以的话我就不特地更新了。

**Comment by XiaoCC** [comment]
@continue-revolution  
![1684060535015-0dc988b7-4802-4deb-bc91-407ca2226835](https://github.com/continue-revolution/sd-webui-segment-anything/assets/7299222/dff9665e-bb9f-417a-8552-492a71c93f7a)
完美解决兼容性问题，👍

**Comment by amimi818** [comment]
> > I found the reason：If "Expand Mask" be checked, the 'NoneType' object has no attribute 'mode'" error is generated, otherwise it is OK.
> 
> Thank you. I rarely use that feature. Will look into the reason after my vacation.

今天又试了一下，已经不报错了（无论是否点选“Expand Mask”），不知道前天怎么回事。
不过“文生图“还是不行（但也不报错），分割生成的蒙版无法传到“图生图”那边。
你这句话”Because ControlNet can inpaint in txt2img. Previously Sam only appears in img2img.“我没太明白。在”文生图“中可以完成分割和蒙版的生成，为什么不能将蒙版发送到”图生图“中呢（点选’switch to inpaint upload‘后，也已经切换到“图生图”的’inpaint upload‘标签下了）？

**Comment by continue-revolution** [comment]
> > > I found the reason：If "Expand Mask" be checked, the 'NoneType' object has no attribute 'mode'" error is generated, otherwise it is OK.
> > 
> > 
> > Thank you. I rarely use that feature. Will look into the reason after my vacation.
> 
> 今天又试了一下，已经不报错了（无论是否点选“Expand Mask”），不知道前天怎么回事。 不过“文生图“还是不行（但也不报错），分割生成的蒙版无法传到“图生图”那边。 你这句话”Because ControlNet can inpaint in txt2img. Previously Sam only appears in img2img.“我没太明白。在”文生图“中可以完成分割和蒙版的生成，为什么不能将蒙版发送到”图生图“中呢（点选’switch to inpaint upload‘后，也已经切换到“图生图”的’inpaint upload‘标签下了）？

文生图你只能在里面传到ControlNet在txt2img下的inpaint，没办法传到img2img。我没有写把文生图中生成的蒙版发送到图生图的代码，也不打算写，这两个是分开的功能，有不同的目的：txt2img下的inpaint完全是为了ControlNet服务，而img2img下的inpaint同时为ControlNet和A1111自带的局部重绘服务

**Comment by amimi818** [comment]
感谢你的耐心解答。
不过既然这样，那文生图里的“Segment Anything”起什么作用呢？而且点按“Segment Anything”下的“switch to inpaint upload”后，也切换到了图生图的“inpaint upload”标签下，容易给人造成seg生成结果可以作用与图生图的错觉。

**Comment by amimi818** [comment]
感谢你的耐心解答。

不过既然这样，那文生图里的“Segment Anything”起什么作用呢？而且点按“Segment Anything”下的“switch to inpaint upload”后，也切换到了图生图的“inpaint upload”标签下，容易给人造成seg生成结果可以作用与图生图的错觉。

我按照说明里的如下步骤操作，在文生图中并未产生预期效果（Seg分割结果并未作用于ControlNet)，不知道是什么问题：

txt2img
1. You may only copy image and mask to ControlNet inpainting.
2. Optionally check ControlNet inpaint not masked to invert mask colors and inpaint regions outside of the mask.
3. Select the correct ControlNet index where you are using inpainting, if you wish to use Multi-ControlNet.
4. Configurate ControlNet panel. Click Enable, preprocessor choose inpaint_global_harmonious, model choose control_v11p_sd15_inpaint [ebff9138]. There is no need to upload image to the ControlNet inpainting panel.
5. Write your prompts, configurate A1111 panel and click Generate.

**Comment by continue-revolution** [comment]
@amimi818 只有你的终端报错了（比如说ControlNet没有接收到control image），才能说明sam生成的mask没有作用到文生图中的ControlNet。我几乎每次测试都是在文生图，所以我可以百分之百肯定文生图是能用的，但是你生成的局部重绘会把蒙版以外的部分也给修改，这是因为lllyasviel是借助A1111的原生局部重绘才实现的仅蒙版重绘（或者说他目前并没有写仅蒙版重绘，也不需要写），otherwise非蒙版区域也会受影响。

**Comment by amimi818** [comment]
我还是不知道问题所在，我文生图中的ControlNet确实没有接收到control image：我选择了“Copy to ControlNet Inpainting”，也Enable了对应编号的ControlNet，而sam生成的蒙版却一点都作用不到文生图的ControlNet上，终端提示：ValueError: controlnet is enabled but no input image is given.

我的ControlNet版本是 v1.1.166，A1111也是1.1版本。

不知你能否录一段文生图上使用的demo。

**Comment by amimi818** [comment]
> 我还是不知道问题所在，我文生图中的ControlNet确实没有接收到control image：我选择了“Copy to ControlNet Inpainting”，也Enable了对应编号的ControlNet，而sam生成的蒙版却一点都作用不到文生图的ControlNet上，终端提示：ValueError: controlnet is enabled but no input image is given.
> 
> 我的ControlNet版本是 v1.1.166，A1111也是1.1版本。
> 

升级ControlNet和A1111 WebUI后（1.2.1） 已经可以在文生图中使用Sem了。

但是在文生图中使用Sem，选择ControlNet inpaint not masked，蒙版的内容也会被进行了一定重绘（尤其是颜色），不知道是ControlNet的问题还是Sem/插件的问题

**Comment by continue-revolution** [comment]
@amimi818 ControlNet的问题。仅重绘选中区域很难实现，ControlNet是靠A1111自带的功能实现的仅重绘选中区域。具体来源可以参考ControlNet issue。

**Comment by amimi818** [comment]
> 

明白了，多谢！

**Comment by Dinh6789** [comment]
my pc is same this error, how to fix it ?
