### ISSUE TITLE
[Bug]: sd-webui cannot detect the sam mode

### ISSUE THREAD

**Issue by zxwmol** [continue-revolution/sd-webui-segment-anything#96]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you updated WebUI and this extension to the newest version?

- [X] I have updated WebUI and this extension to the most up-to-date version

### Do you understand that you should go to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues if you cannot install GroundingDINO?

- [X] My problem is not about installing GroundingDINO

### Do you know that you should use the newest ControlNet extension and enable external control if you want SAM extension to control ControlNet?

- [X] I have updated ControlNet extension and enabled "Allow other script to control this extension"

### What happened?

I have installed the Segment Anything plugin and downloaded the sam_vit_l_0b3195.pth model, which I placed in the /models/sam directory. However, the sd-webui cannot detect the sam model and the page displays a null prompt.

### Steps to reproduce the problem

![image](https://github.com/continue-revolution/sd-webui-segment-anything/assets/38974244/e3db356a-e50d-48d6-b677-7ee0f9978e13)

### What should have happened?

![image](https://github.com/continue-revolution/sd-webui-segment-anything/assets/38974244/3b300c5d-9c76-4e01-ae2f-bfa0e51adbcf)

### Commit where the problem happens

webui: 22bcc7b    https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81
extension: 040312a   https://github.com/continue-revolution/sd-webui-segment-anything/commit/040312a1c85ba92f02bd041ce571f8d793fe8114

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--theme dark --port 8080 --xformers --api --autolaunch --server-name 0.0.0.0 --enable-insecure-extension-access
```

### Console logs

```Shell
Start semantic segmentation with processor seg_ufade20k
Traceback (most recent call last):
  File "C:\BaiduNetdiskDownload\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\BaiduNetdiskDownload\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\BaiduNetdiskDownload\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\BaiduNetdiskDownload\sd-webui-aki-v4\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\BaiduNetdiskDownload\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\BaiduNetdiskDownload\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\BaiduNetdiskDownload\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\sam.py", line 317, in cnet_seg
    sam = load_sam_model(sam_model_name)
  File "C:\BaiduNetdiskDownload\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\sam.py", line 73, in load_sam_model
    model_type = '_'.join(sam_checkpoint.split('_')[1:-1])
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by continue-revolution** [comment]
你可以把模型放到插件目录下的models/sam下再试试。你需要删除webui/models/samxia

**Comment by ChinSiroyugi** [comment]
> 你可以把模型放到插件目录下的models/sam下再试试。你需要删除webui/models/sam目录

![image](https://github.com/continue-revolution/sd-webui-segment-anything/assets/56082791/3facb9cb-20b2-47aa-a899-009b3e7a64b0)

- Here's the document that mentioned the install process.



- Maybe you need to edit the document.

> Change the path from `${sd-webui}/models/sam` to` ${sd-webui}/extensions/sd-webui-segment-anything/models/sam`.

![image](https://github.com/continue-revolution/sd-webui-segment-anything/assets/56082791/bdc9aa3e-77cd-461e-9671-37b5436c6ed6)


（上面英文是发给老外看的，zhang佬加油💪！插件很好用！）

**Comment by continue-revolution** [comment]
@ChinSiroyugi 这个issue的作者用的秋叶整合包，感觉应该是中国人。

按道理来说这两个目录都可以用，至少我用的是我readme里写的这个path。但是如果有一个因为某些莫名其妙的原因用不了了，就可以试试另一个。

**Comment by ChinSiroyugi** [comment]
> @ChinSiroyugi 这个issue的作者用的秋叶整合包，感觉应该是中国人。
> 
> 按道理来说这两个目录都可以用，至少我用的是我readme里写的这个path。但是如果有人因为某些莫名其妙的原因用不了了，就可以试试另一个。

！！！哈哈哈哈哈哈，我的，我以为这是个老外。

我也是不能用默认的`${sd-webui}/models/sam`这个path.
想着来issue里看看有没有人跟我是同样的问题，我提一嘴。

**Comment by cbstyle** [comment]
same problem

**Comment by continue-revolution** [comment]
@cbstyle https://github.com/continue-revolution/sd-webui-segment-anything/issues/96#issuecomment-1552306522

**Comment by continue-revolution** [comment]
closed via https://github.com/continue-revolution/sd-webui-segment-anything#installation

pick another path if you meet the same problem. follow instruction in the README
