### ISSUE TITLE
GroundingDINO安装报错解决办法

### ISSUE THREAD

**Issue by momomomomomomo** [continue-revolution/sd-webui-segment-anything#98]
https://www.bilibili.com/video/BV1AX4y117Qv/
秋叶版Dreambooth和GroundingDINO安装报错解决教程

**Comment by continue-revolution** [comment]
This video (Chinese) might also be helpful if anyone cannot install GroundingDINO. However, I myself develop on linux, so I cannot guarantee any tutorial will work.

https://www.bilibili.com/video/BV1Vh411F7Zn

**Comment by continue-revolution** [comment]
closed via https://github.com/continue-revolution/sd-webui-segment-anything/releases/tag/v1.5.0
