### ISSUE TITLE
[Bug]: User interface of SAM doesnt show in SD Webui

### ISSUE THREAD

**Issue by kaitmax** [continue-revolution/sd-webui-segment-anything#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you updated WebUI and this extension to the newest version?

- [X] I have updated WebUI and this extension to the most up-to-date version

### Do you understand that you should go to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues if you cannot install GroundingDINO?

- [X] My problem is not about installing GroundingDINO

### Do you know that you should use the newest ControlNet extension and enable external control if you want SAM extension to control ControlNet?

- [X] I have updated ControlNet extension and enabled "Allow other script to control this extension"

### What happened?

when i install the extention from url, the SAM dosent show in the stable diffusion webui 

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...
Install SAM Extension

### What should have happened?

SAM UI

### Commit where the problem happens

webui: 
extension: 

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
not applied
```

### Console logs

```Shell
not applied
```

**Comment by steploff** [comment]
I have this same problem. Grounding DINO loads. Segment Anything model loads. UI is checked in the extensions box. I get no actual UI interface with the extension at all, though.

**Comment by kaitmax** [comment]
i found the solution, just install it manualy using "pip install segment_anything"

**Comment by steploff** [comment]
nice. i solved my problem, too. turns out my problem was that i didn't have the correct version of Auto1111. So, I had to just update that.
